### PR TITLE
Wrap video coding APIs

### PR DESCRIPTION
**Pull request by zarik5**
Add support for `AMediaCodec` to ndk-sys. I tried to generate the bindings but I was not able to.

### CODE REVIEW

**Comment by MarijnS95** [comment]
Thanks for your contribution @zarik5! I have a similar change queued up, with regenerated bindings, to be published after #178 is merged.

Are you planning to add support `MediaCodec` in the safe `ndk` bindings?

**Comment by zarik5** [comment]
No I don't have plans for now, I don't feel experienced enough with Android to write a safe wrapper.

**Comment by MarijnS95** [comment]
> No I don't have plans for now, I don't feel experienced enough with Android to write a safe wrapper.

Ah, so just using the raw bindings.

You can find a regenerated `ndk-sys` here: https://github.com/MarijnS95/android-ndk-rs/tree/more-sys

**Comment by zarik5** [comment]
> You can find a regenerated ndk-sys here: https://github.com/MarijnS95/android-ndk-rs/tree/more-sys

Oh thank you!

**Comment by zarik5** [comment]
Since you already took care of it I'll close this PR.

**Comment by zarik5** [comment]
@MarijnS95 Do you still plan to merge your `more-sys` branch into the upstream repository?

**Comment by MarijnS95** [comment]
@zarik5 Are you still planning to rework https://github.com/alvr-org/ALVR/blob/master/alvr/experiments/client/src/video_decoder/mediacodec.rs into a wrapper for submission to android-ndk-rs?

If so I can probably see about rebasing and submitting that branch.

**Comment by zarik5** [comment]
> @zarik5 Are you still planning to rework https://github.com/alvr-org/ALVR/blob/master/alvr/experiments/client/src/video_decoder/mediacodec.rs into a wrapper for submission to android-ndk-rs?

Not really for now, but I think there would still value in having the raw MediaCodec API in the ndk-sys crate. I'm not excluding I will contribute the safe bindings in the future 🙂

**Pull request closed without merging**
