### PR TITLE
ndk-build: Add `ndk_gdb()` function to acquire `ndk-gdb` script path with the correct per-platform extension

### PR DESCRIPTION
**Pull request by Jasper-Bekkers**
The path to the gdb script wasn't generated properly (was missing the `.cmd` extension) and the `detect_abi` was similarly broken on windows.

### CODE REVIEW

**Comment by MarijnS95** [comment]
See also https://github.com/rust-windowing/android-ndk-rs/pull/258, nobody tested it but I don't remember what was wrong with it.

**Comment by Jasper-Bekkers** [comment]
This PR has been tested and is in active use at least.

**Comment by Jasper-Bekkers** [comment]
Rebased :-)

**Comment by MarijnS95** [comment]
Thanks, but I think this may conflict with #331 which I was looking at getting in first :grimacing:

**Comment by Jasper-Bekkers** [comment]
No worries, I can rebase again after.

**Review by MarijnS95 — APPROVED** [review]

**Pull request merged**
