### PR TITLE
Added libs search paths listed by build scripts to help find dylibs

### PR DESCRIPTION
**Pull request by katyo**
Possible fix for #65 
Needed for katyo/oboe-rs#5

Ready to merge.

### CODE REVIEW

**Comment by endragor** [comment]
Works for me on oboe-rs `master` with `OpenSLES` linking fix. Thank you for this fix!

**Comment by francesca64** [comment]
Thanks for making a PR!

@msiglreith do you have any thoughts on this, since you suggested this approach?

**Review by msiglreith — APPROVED** [review]
thanks, lgtm (:

(wasn't watching this repository so far 👀)

**Comment by endragor** [comment]
Would really appreciate it if you could release a version with this fix. This was a stopping issue for making https://github.com/RustAudio/cpal work on Android.

**Comment by francesca64** [comment]
@endragor thanks to #71, creating new releases should now be as simple as making a PR that bumps the Cargo.toml versions of the relevant crates! So you (or anyone else) could beat me to doing that.

**Comment by francesca64** [comment]
New release PR here: #72

**Pull request merged**
