### PR TITLE
Improve repository documentation

### PR DESCRIPTION
**Pull request by msiglreith**
Tried to improve the general documentation of the repository and crates to make it easier to discover features and getting started.

### CODE REVIEW

**Comment by charleschege** [comment]
I have tried adding the `[[package.metadata.android.permission]] ` from this pull request and it is returning an error

```
AndroidManifest.xml:13: error: Error parsing XML: not well-formed (invalid token)

Error: Command '/usr/local/android/sdk/build-tools/28.0.3/aapt package -f -F /home/user/projects/orbandroid/target/debug/apk/orbandroid-unaligned.apk -M AndroidManifest.xml -I /usr/local/android/sdk/platforms/android-29/android.jar' had a non-zero exit code
```

**Comment by dvc94ch** [comment]
Thanks @msiglreith

**Comment by MarijnS95** [comment]
@msiglreith Was the `ndk-examples` removal (as previously discussed) removed from https://github.com/rust-windowing/android-ndk-rs/commit/0cc97ff2b67cb70860edd63bf5c859b33ffa3f4b in favour of submitting that in a separate PR?

https://github.com/rust-windowing/android-ndk-rs/issues/48 is not properly resolved yet without that. Would you mind if I re-apply and PR the change?

**Comment by msiglreith** [comment]
@MarijnS95 Feel free to file a PR! I revert it as it didn't pan out as expected, but I don't recall the exact issues I had with removing `ndk-examples`. I think part of it was separating the manifest from the from cargo library (e.g for asset paths, crate-type, etc.)

**Comment by MarijnS95** [comment]
@msiglreith That'd be for a more elaborate example I guess? In that case we're better off making `ndk-examples` _the_ example instead of the empty lib it is now. That saves polluting `ndk-glue` as [previously proposed](https://github.com/rust-windowing/android-ndk-rs/issues/48#issuecomment-656931548).

We should probably add a very simple looper to prevent the example from locking up and crashing, too.

**Comment by dvc94ch** [comment]
I don't think this is necessary, just because people are too lazy to read the documentation or notice that the crate follows standard cargo conventions and the tool standard cargo cli options

**Comment by MarijnS95** [comment]
@dvc94ch to be fair I have - in my limited Rust career - not seen a single example stuffed in an otherwise empty library project yet. Either the project _is_ the example, or the example is integrated with one of the top-level packages.

**Pull request merged**
